### PR TITLE
Use libsecret from shared-modules

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by mhoeher** [comment]
Hi @Lctrs and @TingPing,

thanks for taking care of this change!

**Comment by Lctrs** [comment]
@mhoeher It has been merged into the beta branch. Could you take care of merging this change into master please ?

**Comment by mhoeher** [comment]
@Lctrs Sure, I'll include it in the next release (due end of the month if everything goes well).

**Comment by Lctrs** [comment]
Thanks !

**Pull request merged**
